Repository jenkins-x/updatebot, pull requests merged in 2019-03, with the labels that each got.

#74 lets also check the HOME env var when looking for git credentials as tekton changes the users home dir
  updatebot-core/src/main/java/io/jenkins/updatebot/commands/CommandSupport.java
Labels: approved, size/XS

#73 Stop mixing prs across branches
  updatebot-core/src/main/java/io/jenkins/updatebot/commands/ModifyFilesCommandSupport.java
  updatebot-core/src/main/java/io/jenkins/updatebot/git/GitPluginCLI.java
Labels: approved, lgtm, ok-to-test, size/M

#75 chore: changing downstream repo for updatebot
  .updatebot.yml
Labels: approved, lgtm, size/XS

#76 feat: enable recursivly searching for dockerfiles in subdirectories
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/docker/DockerUpdater.java
Labels: approved, size/M

#77 lets update the builders-base repo now that updatebot has moved
  .updatebot.yml
Labels: approved, size/XS

#78 feat: can batch up regex updates into a single push
  updatebot-core/src/main/java/io/jenkins/updatebot/commands/PushRegexChanges.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/regex/RegexUpdater.java
  updatebot-core/src/main/java/io/jenkins/updatebot/support/FileMatcher.java
Labels: approved, size/M

#79 feat: added ARG to Dockerfile update & added tests
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/docker/DockerUpdater.java
  updatebot-core/src/test/java/io/jenkins/updatebot/kind/docker/ReplaceDockerfileStatementTest.java
Labels: approved, size/L

#82 Add jenkins-x pipeline updater
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/Kind.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/jenkinsx/JenkinsXUpdater.java
  updatebot-core/src/test/java/io/jenkins/updatebot/kind/jenkinsx/ReplaceJenkinsXfileStatementTest.java
Labels: approved, lgtm, size/L

#83 chore: minor warning fix, improved logging
  updatebot-core/src/main/java/io/jenkins/updatebot/commands/CommandSupport.java
  updatebot-core/src/main/java/io/jenkins/updatebot/commands/ModifyFilesCommandSupport.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/helm/HelmUpdater.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/maven/PomUpdateStatus.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/plugins/PluginVersions.java
  updatebot-core/src/main/java/io/jenkins/updatebot/kind/regex/RegexUpdater.java
  updatebot-core/src/main/java/io/jenkins/updatebot/support/FileMatcher.java
  updatebot-core/src/test/java/io/fabric8/updatebot/BrewPushSourceDependenciesTest.java
Labels: approved, size/M
